/**
 * Serialize collections into the nine export formats Sepia supports.
 *
 * Consumers (the ExportModal UI and the Electron main process) pass in the
 * already-resolved color list for each collection, so this file stays pure
 * and doesn't touch the store directly. ASE is the only binary format; it
 * returns a base64 string so the same IPC payload shape works for all.
 */
import { SavedColor, Collection, ExportFormat } from '../types';

// ---------------------------------------------------------------------------
// Shared helpers
// ---------------------------------------------------------------------------

/** Normalize an arbitrary string into a safe CSS/SCSS/JSON identifier. */
export function slugify(name: string): string {
  const s = name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '');
  return s || 'color';
}

export function extensionFor(format: ExportFormat): string {
  switch (format) {
    case 'css': return '.css';
    case 'scss': return '.scss';
    case 'tailwind': return '.js';
    case 'json': return '.json';
    case 'ase': return '.ase';
    case 'sketch': return '.sketchpalette';
    case 'figma-tokens': return '.json';
    case 'gpl': return '.gpl';
    case 'raw': return '.txt';
  }
}

interface ExportResult {
  content: string; // base64 for binary formats
  isBinary: boolean;
  extension: string;
}

// ---------------------------------------------------------------------------
// Text format generators
// ---------------------------------------------------------------------------

function toCss(collections: Array<{ name: string; colors: SavedColor[] }>): string {
  const lines: string[] = [':root {'];
  for (const c of collections) {
    const slug = slugify(c.name);
    lines.push(`  /* Collection: ${c.name} */`);
    c.colors.forEach((color, i) => {
      lines.push(`  --${slug}-${i + 1}: ${color.hex};`);
    });
  }
  lines.push('}');
  return lines.join('\n') + '\n';
}

function toScss(collections: Array<{ name: string; colors: SavedColor[] }>): string {
  const lines: string[] = [];
  for (const c of collections) {
    const slug = slugify(c.name);
    lines.push(`// Collection: ${c.name}`);
    c.colors.forEach((color, i) => {
      lines.push(`$${slug}-${i + 1}: ${color.hex};`);
    });
    lines.push('');
  }
  return lines.join('\n');
}

function toTailwind(collections: Array<{ name: string; colors: SavedColor[] }>): string {
  const colorMap: Record<string, string> = {};
  for (const c of collections) {
    const slug = slugify(c.name);
    c.colors.forEach((color, i) => {
      colorMap[`${slug}-${i + 1}`] = color.hex;
    });
  }
  const body = JSON.stringify(colorMap, null, 2).replace(/"/g, "'");
  return `// Generated by Sepia — paste into your tailwind.config.js\nmodule.exports = {\n  theme: {\n    extend: {\n      colors: ${body}\n    }\n  }\n};\n`;
}

function toJson(collections: Array<{ name: string; colors: SavedColor[] }>): string {
  const out = collections.map((c) => ({
    name: c.name,
    colors: c.colors.map((color) => ({
      hex: color.hex,
      rgb: [color.rgb.r, color.rgb.g, color.rgb.b],
      hsl: [color.hsl.h, color.hsl.s, color.hsl.l],
    })),
  }));
  return JSON.stringify(
    collections.length === 1 ? out[0] : { collections: out },
    null,
    2,
  ) + '\n';
}

function toSketch(collections: Array<{ name: string; colors: SavedColor[] }>): string {
  const all: SavedColor[] = collections.flatMap((c) => c.colors);
  const payload = {
    compatibleVersion: '2.0',
    pluginVersion: '2.2',
    colors: all.map((c) => ({
      red: +(c.rgb.r / 255).toFixed(3),
      green: +(c.rgb.g / 255).toFixed(3),
      blue: +(c.rgb.b / 255).toFixed(3),
      alpha: 1,
    })),
  };
  return JSON.stringify(payload, null, 2) + '\n';
}

function toFigmaTokens(collections: Array<{ name: string; colors: SavedColor[] }>): string {
  const out: Record<string, Record<string, { value: string; type: 'color' }>> = {};
  for (const c of collections) {
    const slug = slugify(c.name);
    out[slug] = {};
    c.colors.forEach((color, i) => {
      out[slug][`color-${i + 1}`] = { value: color.hex, type: 'color' };
    });
  }
  return JSON.stringify(out, null, 2) + '\n';
}

function toGpl(collections: Array<{ name: string; colors: SavedColor[] }>): string {
  const name = collections.length === 1 ? collections[0].name : 'Sepia Export';
  const lines: string[] = ['GIMP Palette', `Name: ${name}`, 'Columns: 4', '#'];
  for (const c of collections) {
    const slug = slugify(c.name);
    c.colors.forEach((color, i) => {
      const pad = (n: number) => String(n).padStart(3, ' ');
      lines.push(`${pad(color.rgb.r)} ${pad(color.rgb.g)} ${pad(color.rgb.b)}\t${slug}-${i + 1}`);
    });
  }
  return lines.join('\n') + '\n';
}

function toRaw(collections: Array<{ name: string; colors: SavedColor[] }>): string {
  return collections.flatMap((c) => c.colors.map((x) => x.hex)).join('\n') + '\n';
}

// ---------------------------------------------------------------------------
// ASE (Adobe Swatch Exchange) binary format
// ---------------------------------------------------------------------------
// NOTE: ASE is a well-known but fiddly binary format. This implementation
// writes the minimal valid structure: magic "ASEF", version 1.0, a block
// count, then one color block per color (no groups). It has been validated
// against the public spec (https://www.selapa.net/swatches/colors/fileformats.php)
// but may show slightly different metadata in some editors vs. a native save.

function toAseBase64(collections: Array<{ name: string; colors: SavedColor[] }>): string {
  const chunks: Buffer[] = [];

  // Helper: write a big-endian UTF-16 null-terminated string with length prefix
  const encodeString = (str: string): Buffer => {
    const chars = str + '\u0000';
    const buf = Buffer.alloc(2 + chars.length * 2);
    buf.writeUInt16BE(chars.length, 0);
    for (let i = 0; i < chars.length; i++) {
      buf.writeUInt16BE(chars.charCodeAt(i), 2 + i * 2);
    }
    return buf;
  };

  const allColors = collections.flatMap((c) =>
    c.colors.map((color, i) => ({ color, name: `${slugify(c.name)}-${i + 1}` })),
  );

  // Header: "ASEF" + version 1.0 + block count
  const header = Buffer.alloc(12);
  header.write('ASEF', 0, 4, 'ascii');
  header.writeUInt16BE(1, 4);
  header.writeUInt16BE(0, 6);
  header.writeUInt32BE(allColors.length, 8);
  chunks.push(header);

  // Color blocks
  for (const { color, name } of allColors) {
    const nameBuf = encodeString(name);
    const modelBuf = Buffer.from('RGB ', 'ascii');
    const rgbBuf = Buffer.alloc(12);
    rgbBuf.writeFloatBE(color.rgb.r / 255, 0);
    rgbBuf.writeFloatBE(color.rgb.g / 255, 4);
    rgbBuf.writeFloatBE(color.rgb.b / 255, 8);
    const typeBuf = Buffer.alloc(2);
    typeBuf.writeUInt16BE(0x0002, 0); // Global color

    const body = Buffer.concat([nameBuf, modelBuf, rgbBuf, typeBuf]);
    const blockHeader = Buffer.alloc(6);
    blockHeader.writeUInt16BE(0x0001, 0); // Color entry type
    blockHeader.writeUInt32BE(body.length, 2);
    chunks.push(blockHeader, body);
  }

  return Buffer.concat(chunks).toString('base64');
}

// ---------------------------------------------------------------------------
// Public entry points
// ---------------------------------------------------------------------------

function generate(
  groups: Array<{ name: string; colors: SavedColor[] }>,
  format: ExportFormat,
): ExportResult {
  switch (format) {
    case 'css':
      return { content: toCss(groups), isBinary: false, extension: extensionFor(format) };
    case 'scss':
      return { content: toScss(groups), isBinary: false, extension: extensionFor(format) };
    case 'tailwind':
      return { content: toTailwind(groups), isBinary: false, extension: extensionFor(format) };
    case 'json':
      return { content: toJson(groups), isBinary: false, extension: extensionFor(format) };
    case 'sketch':
      return { content: toSketch(groups), isBinary: false, extension: extensionFor(format) };
    case 'figma-tokens':
      return { content: toFigmaTokens(groups), isBinary: false, extension: extensionFor(format) };
    case 'gpl':
      return { content: toGpl(groups), isBinary: false, extension: extensionFor(format) };
    case 'raw':
      return { content: toRaw(groups), isBinary: false, extension: extensionFor(format) };
    case 'ase':
      return { content: toAseBase64(groups), isBinary: true, extension: extensionFor(format) };
  }
}

export function exportCollection(
  collection: Collection,
  colors: SavedColor[],
  format: ExportFormat,
): ExportResult {
  return generate([{ name: collection.name, colors }], format);
}

export function exportAll(
  collections: Collection[],
  allColors: SavedColor[],
  format: ExportFormat,
): ExportResult {
  const byId: Record<string, SavedColor> = {};
  for (const c of allColors) byId[c.id] = c;
  const groups = collections.map((col) => ({
    name: col.name,
    colors: col.colorIds.map((id) => byId[id]).filter((x): x is SavedColor => !!x),
  }));
  return generate(groups, format);
}

/** Friendly labels for the ExportModal dropdown. */
export const EXPORT_FORMAT_LABELS: Record<ExportFormat, string> = {
  css: 'CSS Variables',
  scss: 'SCSS Variables',
  tailwind: 'Tailwind Config',
  json: 'JSON',
  ase: 'Adobe Swatch (.ase)',
  sketch: 'Sketch Palette',
  'figma-tokens': 'Figma Tokens',
  gpl: 'GIMP Palette (.gpl)',
  raw: 'Raw text',
};
